name: AgroAI CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Install Frontend Dependencies
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      # Build Frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # Build Docker Containers
      - name: Build Docker Images
        run: docker compose build

      # Success Message
      - name: CI Success
        run: echo "GitHub Actions CI Pipeline Working Successfully"